# Generated by Django 4.2.3 on 2023-08-06 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_alter_contact_options_alter_contact_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_followers',
            field=models.BooleanField(default=False),
        ),
    ]
